### ISSUE TITLE
[other] Flow of README should be consistent

### ISSUE THREAD

**Issue by jodeck80** [SoftwareEngineeringToolDemos/FSE-2014-ConceptCloud#9]
Criteria for issue:

Are there any other ways the readme is not consistent with the example readme or other readmes in the organization?

Most other repos begin readme with "This repository contains information related to the tool", and then has further description below. ConceptCloud has the full description above. Ensure order aligns with other repos and what professor intends. This may be a non issue.

**Comment by gauri145** [comment]
Any additional information other than that described in the sample repository readme may be included as long as the README contains all the information mentioned in the sample repository. But still I have  removed the additional information from the README so that it looks exactly as given in the sample repository readme.

**Comment by gauri145** [comment]
The additional information provided earlier has been removed and the README has been made consistent.
